[package]
name = "bevy_oxr"
version = "0.1.0"
edition = "2021"
description = "Community crate for OpenXR in Bevy"
repository = "https://github.com/awtterpip/bevy_oxr"
license = "MIT/Apache-2.0"

[dependencies]
bevy_openxr.path = "./crates/bevy_openxr"
bevy_xr.path = "./crates/bevy_xr"
bevy = "0.13.0"

[workspace]
members = ["crates/*", "crates/bevy_openxr/examples/android"]

[workspace.dependencies]
bevy = { git = "https://github.com/awtterpip/bevy.git", branch = "multiview-0.13.2" }
